### ISSUE TITLE
Voronoi hotfix returns values are not rendering

### ISSUE THREAD

**Issue by iriberri** [CartoDB/crankshaft#113]
In the process of releasing the last Voronoi fix related with the projections (https://github.com/CartoDB/crankshaft/pull/112) I found out that the function seems to be returning "invalid" geometries.

```sql
WITH a AS (
    SELECT
    ARRAY[ST_GeomFromText('POINT(2.1744 41.403)', 4326),ST_GeomFromText('POINT(2.1228 41.380)', 4326),ST_GeomFromText('POINT(2.1511 41.374)', 4326),ST_GeomFromText('POINT(2.1528 41.413)', 4326),ST_GeomFromText('POINT(2.165 41.391)', 4326),ST_GeomFromText('POINT(2.1498 41.371)', 4326),ST_GeomFromText('POINT(2.1533 41.368)', 4326),ST_GeomFromText('POINT(2.131386 41.41399)', 4326)] AS geomin
),
b as(
    SELECT
       cdb_crankshaft.CDB_voronoi(geomin, 0.2, 1e-9) as result
    FROM a
)
SELECT
    result::text
FROM b
````

The Builder fails when rendering the result:

![image](https://cloud.githubusercontent.com/assets/1730320/17768342/ddda2362-6533-11e6-8fe0-fa26d201a252.png)

Without this fix, queries such as
```sql
SELECT cdb_crankshaft.CDB_Voronoi(array_agg(the_geom))  from new_york_new_york_osm_point_copy
``` 

were immediately working in the Builder.

Trying to wrap the geom in the function `ST_AsGeoJSON` gives:

```javascript
{
error: [
"GeoJson: geometry not supported."
]
}
````

while using `ST_AsText` with the query below gives a geometry collection of polygons and a line around coords `(2.11161306104778 41.3973796779823)`

```sql
WITH a AS (
    SELECT
    ARRAY[ST_GeomFromText('POINT(2.1744 41.403)', 4326),ST_GeomFromText('POINT(2.1228 41.380)', 4326),ST_GeomFromText('POINT(2.1511 41.374)', 4326),ST_GeomFromText('POINT(2.1528 41.413)', 4326),ST_GeomFromText('POINT(2.165 41.391)', 4326),ST_GeomFromText('POINT(2.1498 41.371)', 4326),ST_GeomFromText('POINT(2.1533 41.368)', 4326),ST_GeomFromText('POINT(2.131386 41.41399)', 4326)] AS geomin
)
SELECT
    st_astext(st_transform(cdb_crankshaft.CDB_voronoi(geomin, 0.2, 1e-9), 4326)) as result
FROM a
````

Also, running a `ST_SRID` over the result returns 4326.

**Comment by iriberri** [comment]
cc @rafatower

**Comment by iriberri** [comment]
And basically, the query:

````
WITH a AS (
    SELECT
    ARRAY[ST_GeomFromText('POINT(2.1744 41.403)', 4326),ST_GeomFromText('POINT(2.1228 41.380)', 4326),ST_GeomFromText('POINT(2.1511 41.374)', 4326),ST_GeomFromText('POINT(2.1528 41.413)', 4326),ST_GeomFromText('POINT(2.165 41.391)', 4326),ST_GeomFromText('POINT(2.1498 41.371)', 4326),ST_GeomFromText('POINT(2.1533 41.368)', 4326),ST_GeomFromText('POINT(2.131386 41.41399)', 4326)] AS geomin
)
SELECT
    st_astext(st_transform(cdb_crankshaft.CDB_voronoi(geomin, 0.2, 1e-9), 4326)) as result
FROM a
````

returns a MultiPolygon in production (before hotfix) and a GeometryCollection with the hotfix (as I said before, it has polygons and a line).

**Comment by rafatower** [comment]
The postgis function returns a GEOMETRYCOLLECTION with POLYGONs:

http://postgis.net/docs/manual-dev/ST_Voronoi.html

with no LINE on it (depending on `return_polygons` param).

Our function, as per the docs, should NOT return LINEs: https://github.com/CartoDB/crankshaft/blob/develop/doc/09_voronoi.md#returns

I'd stick to the original API. This is worth a test.

**Comment by iriberri** [comment]
By the way, trying to look into the issue I found this: http://postgis.refractions.net/documentation/manual-2.1SVN/ST_CollectionExtract.html, but no idea if we can avoid the line in any other way.

**Comment by AbelVM** [comment]
Ooops, I was using this test:

```sql
WITH a AS (
    SELECT
          array_agg(the_geom) as geomin
      FROM centros_comerciales_de_madrid
)
SELECT
    st_transform(
	(st_dump(CDB_voronoi(geomin, 0.2, 1e-9)
	)).geom
        , 3857) as the_geom_webmercator
FROM a    
```

So I added the dump stuff outside the function. The fix to the fix is coming soon to a PR close to you

**Comment by AbelVM** [comment]
It was related to:
* degenerated polygons that turned into lines
* 1-point-spikes in polygons

FIxed by https://github.com/CartoDB/crankshaft/pull/114
