### ISSUE TITLE
New Analysis Idea - Geographically Weighted Regression

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/crankshaft#115]
## Description

Analysis to generate a GLM model and find spatial dependance of multiple variables on a target variable. Outputs the dependance of the target variable on each of the explanatory variables, the intercept in each location and the goodness of fit for each region. 

Example from Georgia where the dependent variable is % bachelor and the dependent variables are % black, % rural, % poverty can be seen [here](https://team.carto.com/u/stuartlynn/builder/4e0432b4-687b-11e6-a06a-0e3a376473ab/embed)
## Inputs
- Layer with points, polygons or lines 
- Column to use for target variable
- Columns to use as explanatory variables
- Model family
- Bandwidth, or bandwidth discovery method
## Outputs
- A table with the original geometries, the goodness of fit of the analysis, the intercept for each region and the slopes for each explanatory variable in each region.
## Usecases
- Starts to get at dependance, correlation within regions

**Comment by andy-esch** [comment]
Done in #146
