### ISSUE TITLE
Release next crankshaft version

### ISSUE THREAD

**Issue by iriberri** [CartoDB/crankshaft#130]
This will include:

* Let the user set the resolution [19]: https://github.com/CartoDB/crankshaft/pull/120
* [interpolation] Add NN(s) method: https://github.com/CartoDB/crankshaft/pull/129
* Improve error reporting for moran and markov https://github.com/CartoDB/crankshaft/pull/123

**Comment by iriberri** [comment]
Hey @AbelVM,

* In the NNs PR I think you still have some changes pending after my review, right? (return values docs + unused variable)
* For the resolution issue, I don't know if you plan to make any change after the conversation from yesterday re: function signature changes in extensions

Just let me know so that I can proceed ;)

**Comment by iriberri** [comment]
@ohasselblad if any of your PRs has been reviewed and is good to go, please link it here and I'll take it out! :)

**Comment by AbelVM** [comment]
#120 : the new format does not change the signature, and makes sense for the full chain, so it's OK this way

#129 : d'you mean documenting the `-XXX.xx` values? I'll fix it asap.

**Comment by AbelVM** [comment]
#129 added docs, ok to go

**Comment by iriberri** [comment]
Thanks @AbelVM!

**Comment by AbelVM** [comment]
:+1:

**Comment by ohasselblad** [comment]
#123 is all ready to go!

**Comment by iriberri** [comment]
Perfect timing @ohasselblad! I'll start the release pretty soon :) I think that I'm closing the list with that one. Thanks!

**Comment by iriberri** [comment]
0.4.1 is in master. Still not deployed but I can close the issue, which was mostly for coordination.

Thanks all!
