### ISSUE TITLE
Execute Moran without geometries should fail?

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/crankshaft#143]
I've executed the `CDB_AreasOfInterestLocal` function against the [NYPD crime locations data](https://data.cityofnewyork.us/Public-Safety/NYPD-7-Major-Felony-Incident-Map/dvh8-u7es) but without georeference it (no geometries) and the analysis worked with it until I killed the process.

My question is, shouldn't the function return an error or empty when there are no geometries to compare KNN? (Maybe I'm asking some stupid question but just in case...)

**Comment by ohasselblad** [comment]
@ethervoid good question. We actually never check for null geoms in the query: https://github.com/CartoDB/crankshaft/blob/ecb4bd96060aab55819111ac600fb65db2449a53/src/py/crankshaft/crankshaft/pysal_utils/pysal_utils.py#L120-L149

It checks for the null-valued numeric column values but not the geoms.
