### ISSUE TITLE
[crankshaft] deploy new functions and fixes

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/crankshaft#159]
The following PRs are ready to be included in a new release:

* ~GWR: #146~ released in #184 
* Nonspatial k-means: #150
* ~Better docs on function usage: #155~
* ~Refactoring of analysis data providers to provide less error prone errors: https://github.com/CartoDB/crankshaft/pull/157~
* PIA function now accepts multipolygons: https://github.com/CartoDB/crankshaft/pull/165
* Spatial Interaction Models: #147

**Comment by rafatower** [comment]
I'd split this into two tickets

**Comment by ohasselblad** [comment]
Done. Future release request here: https://github.com/CartoDB/crankshaft/issues/161

**Comment by ohasselblad** [comment]
We finished another PR (https://github.com/CartoDB/crankshaft/pull/157). Is there time to add it to this release?

**Comment by rafatower** [comment]
Nobody has worked on it yet, sorry (it's in the TODO list, check the projects). The upside is that scope / issue definition can still be modified.

Feel free to modify this ticket and/or close the other.

**Comment by ohasselblad** [comment]
👍 thanks. Just added one more PR. If I want to add others, I'll message here first.

**Comment by ohasselblad** [comment]
Adding more more PR (#147) which will be completed this week.

**Comment by andy-esch** [comment]
Closing this in favor of #194
