### ISSUE TITLE
DATAOBS- Decide on 'dimension' or 'column' and change through the code and documentation

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/crankshaft#27]
We currently use 'dimension' in the code to refer to a variable in the census. @talos and me where talking about changing this to 'column' and updating throughout the code and documentation to reflect this. 

@andrewxhill Do you have strong feelings about 'dimension' or 'column' ?

**Comment by andrewxhill** [comment]
I was thinking we would want to reserve the use of "column" to only refer to columns of data stored within a user's account. That way, it is very easy to explain how they turn a "Dimension" of data from the DO into a "Column" of data on their own account. What do you think?

**Comment by talos** [comment]
Discussed this today and settled on using the term `measure`.

Should I leave this issue open til all vocab has been switched?

**Comment by ohasselblad** [comment]
we went with measure! See all of the beautiful functions here: https://docs.cartodb.com/cartodb-platform/data/measures-functions/
