### ISSUE TITLE
DATAOBS  - Consistently use the term Augment / Get

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/crankshaft#29]
@talos  and I where talking about our use of the word 'Augment' within the function names. It feels like 'augment' should be used when we are actually updating a table with values and we should instead use 'get' when we are simply returning the variables from the function. 

@andrewxhill what do you think? Will update the Docs and code accordingly

**Comment by andrewxhill** [comment]
+1 for me

**Comment by stuartlynn** [comment]
Ok these are updated to be GET consistently
