### ISSUE TITLE
DATAOBS - Make OBS_LOOKUP_CENSUS_HUMAN more rhobust

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/crankshaft#32]
Currently [OBS_LOOKUP_CENSUS_HUMAN](https://github.com/CartoDB/crankshaft/blob/data_observatory_functions/src/pg/sql/40_observatory_utility.sql#L76)  hard codes the name of the census table to look up. Need to make this less brittle.

**Comment by ohasselblad** [comment]
I believe this is OBS_Search now: https://github.com/CartoDB/observatory-extension/blob/faa3c168dadcad0370a1615c403066e7f963c41b/src/pg/sql/42_observatory_exploration.sql#L52

**Comment by stuartlynn** [comment]
I don't think this is quite obs search but I also don't think we use it anymore, we do the rectified name lookup now.
