### ISSUE TITLE
DATAOBS- Overload the  OBS_AUGMENT_TABLE_WITH_CENSUS function to request multiple variables

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/crankshaft#35]
Currently [OBS_AUGMENT_TABLE_WITH_CENSUS](https://github.com/CartoDB/crankshaft/blob/data_observatory_functions/src/pg/sql/41_observatory_augmentation.sql#L237) can only augment a table with one census variable at a time. Overload it to be able to take an array of variables and augment the table with all of them.

**Comment by andy-esch** [comment]
`OBS_GetData` handles this: https://github.com/CartoDB/observatory-extension/blob/develop/doc/measures_functions.md#obs_getdatageomvals-arraygeomval-metadata-json

@stuartlynn, ok to close this?
