### ISSUE TITLE
DATAOBS- Create OBS_AUGMENT_TABLE_WITH_DEMOGRAPHIC_SNAPSHOT

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/crankshaft#36]
Create version of OBS_AUGMENT_DEMOGRAPHIC_SNAPSHOT that writes all the demographic snapshot variables to  a target table.

@andrewxhill do we need this for QLIK?

**Comment by andrewxhill** [comment]
Nope, not for Qlik
