### ISSUE TITLE
DATAOBS - Versioning of Metadata tables

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/crankshaft#39]
Currently if we change the meta data tables its going to be break the Data Observatory functions. This is going to hinder development etc.

Proposed solution is to have a part of the crankshaft build script detect the build target : development / not development and prefix the names of data_obs tables in the crankshaft code with dev_ etc. Then we can maintain a version of the data observatory tables called dev where work can be done without affecting the live version of the data observatory.

@talos @andrewxhill @ohasselblad thoughts?

**Comment by talos** [comment]
We now have versions in our metadata, although we're not utilizing them in the OBS functions.

**Comment by talos** [comment]
There is now an overarching version for all data and metadata when we generate dumps.  See https://github.com/CartoDB/bigmetadata/blob/master/tasks/carto.py#L366 .
