### ISSUE TITLE
DATAOBS- Scope OBS_LIST_AVAILABLE_SEGMENTS to a particular tag type

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/crankshaft#40]
Currently this returns all kinds of tags, including tags for geometries etc. In the future we will have tag types which we can scope this function to.

**Comment by andy-esch** [comment]
I'm fuzzy on what this is targeting.

There's the segmentation functionality (https://carto.com/docs/carto-engine/dataservices-api/segmentation-functions/) and there's [`OBS_GetCategory`](https://carto.com/docs/carto-engine/data/measures-functions/#obs_getcategorypoint-geometry-category_id-text) and [`OBS_GetData`](https://carto.com/docs/carto-engine/data/measures-functions/#obs_getdatageomvals-arraygeomval-metadata-json) which can accomplish similar outputs. 

@stuartlynn, is this something you'd like scoped out still, or does the existing functionality cover this?

**Comment by stuartlynn** [comment]
I think these where proposed before the OBS API so I think they can be closed for now.
