### ISSUE TITLE
DATAOBS - Pull data from the correct table / data source depending on geom

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/crankshaft#43]
Determine relevant columns based off input geom for a given tag. IE for male_pop requested on a  global dataset , transparently pull from US census in the US pull from UK census in UK etc

**Comment by ohasselblad** [comment]
You did it 👍  https://github.com/CartoDB/observatory-extension/blob/faa3c168dadcad0370a1615c403066e7f963c41b/src/pg/sql/41_observatory_augmentation.sql#L338
