### ISSUE TITLE
DATAOBS - Update OBS_SEARCH to return source column from tag source column

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/crankshaft#44]
Once tags have a source column, return the source form this column instead of extracting it from the colname string like we are now.

https://github.com/CartoDB/crankshaft/blob/data_observatory_functions/src/pg/sql/42_observatory_exploration.sql#L13

**Comment by ohasselblad** [comment]
return value does this: `RETURNS TABLE(id text, description text, name text, aggregate text, source text)  as $$
`
See code here: https://github.com/CartoDB/observatory-extension/blob/faa3c168dadcad0370a1615c403066e7f963c41b/src/pg/sql/42_observatory_exploration.sql#L56
