### ISSUE TITLE
DATAOBS - Crankshaft preprocessing script to automatically populate return types 

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/crankshaft#45]
Currently there is no way to return dynamic table columns from a function. This means for each named segment, we have to hardcode the variable types and names in order to return a table.  For example here :

https://github.com/CartoDB/crankshaft/blob/data_observatory_functions/src/pg/sql/41_observatory_augmentation.sql#L55-L96

We should generate these lists of variables by querying the tag meta-data tables at crankshaft build time  and updating appropriately.

**Comment by andy-esch** [comment]
If I understand the purpose of this ticket correctly, this type of query can be dynamically constructed from the metadata. You can see an example of this in Python in cartoframes: https://github.com/CartoDB/cartoframes/blob/6977ce422f9c1ac4e45f70d10438c36b34f52bd9/cartoframes/context.py#L1624-L1643

Builder/camshaft do something similar: https://github.com/CartoDB/camshaft/blob/bdb63d625552ea1b2fa36650133b5bd51c7a29c1/lib/node/nodes/data-observatory-multiple-measures.js#L110-L119

**Comment by stuartlynn** [comment]
Teah I think this ticket is probably no longer relevant.
