### ISSUE TITLE
DATAOBS - At segments attribution to attributions page

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/crankshaft#53]

**Comment by stuartlynn** [comment]
For reference 

Attribution is : 
Spielman, Seth; Singleton, Alex. Understanding America's Neighborhoods Using Uncertain Data from the American Community Survey: Output Data: US_tract_clusters_new. Ann Arbor, MI: Inter-university Consortium for Political and Social Research [distributor], 2015-07-20. http://doi.org/10.3886/E41546V1

Paper lives here :
http://www.tandfonline.com/doi/pdf/10.1080/00045608.2015.1052335

Data from here: 
https://www.openicpsr.org/repoEntity/show/41528

**Comment by ohasselblad** [comment]
now in docs here: https://docs.cartodb.com/cartodb-platform/data/license/
