### ISSUE TITLE
Should we move CDB_Densify & CDB_TINmap PRs to this repo?

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/crankshaft#65]
https://github.com/CartoDB/cartodb-postgresql/pull/254

**Comment by rafatower** [comment]
+1 to moving that PR here.

Rationale: the scope of responsibility of cartodb-postgresql extension is mostly CARTO metadata management. It shouldn't be mixed with other stuff. OTOH this repo is more suitable for spatial analysis stuff.

cc/ @ohasselblad @stuartlynn

**Comment by stuartlynn** [comment]
👍 Sounds good to me

**Comment by AbelVM** [comment]
Ok, 2 separate PR or just one? Both TINmaps is a side product of Densify

**Comment by rafatower** [comment]
then I'd say one PR (with tests and docs)

**Comment by AbelVM** [comment]
:+1:

**Comment by ohasselblad** [comment]
yep, all sounds good to me :)

**Comment by AbelVM** [comment]
https://github.com/CartoDB/crankshaft/pull/90

**Comment by andy-esch** [comment]
Handled in https://github.com/CartoDB/crankshaft/pull/90
