### ISSUE TITLE
Analysis Request: Near Function 

### ISSUE THREAD

**Issue by nygeog** [CartoDB/crankshaft#85]
One function that I really like is calculating the distance from one dataset's features to another dataset's nearest features. Would love to help out.

Perhaps my dated slides would help convey the functionality. 

![](https://dl.dropboxusercontent.com/u/36281098/class/_lectures/13_geoprocessing/assets/images-1/s13.b.jpeg?ts=2013-03-12%2013%3A32%3A56)

![](https://dl.dropboxusercontent.com/u/36281098/class/_lectures/13_geoprocessing/assets/images-1/s14.b.jpeg?ts=2013-03-12%2013%3A32%3A56)

**Comment by AbelVM** [comment]
I'll take it

**Comment by AbelVM** [comment]
https://github.com/CartoDB/camshaft/pull/171
